#!/bin/sh
browserlist="qutebrowser
firefox
chrome"
browser="$(echo "$browserlist" | rofi -p browser -dmenu)"
case $browser in
	qutebrowser)
		qutebrowser;;
	firefox)
		firefox-bin;;
	chrome)
		google-chrome-stable;;
esac
