#!/bin/sh
browserlist="qutebrowser
firefox
chrome"
browser="$(echo "$browserlist" | bemenu -p browser -m all)"
case $browser in
	qutebrowser)
		qutebrowser;;
	firefox)
		firefox-bin;;
	chrome)
		google-chrome-stable;;
esac
