" make vim respect XDG standards
set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" UI settings
set noswapfile
set mouse +=a

" appearence
set background=dark
set number

" 2 space indent 
set shiftwidth=2
set smarttab
set expandtab
set softtabstop=0
set tabstop=8
